title: Alex Maksimov's blog
email: maleksware@gmail.com
description: >-
  Hello, I'm Alex Maksimov, a young student and Python developer.
  I like competitive programming and APIs.
  If you'd like to learn more about me, visit my GitHub: maleksware
# url: "maleksware.github.io/blog-backup/"
github_username:  maleksware
permalink: /:title/
encoding: utf-8
# Build settings
remote_theme: "mmistakes/minimal-mistakes"
#theme: minimal-mistakes-jekyll
plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-remote-theme
  - jekyll-spaceship
minimal_mistakes_skin: "sunrise"
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: single



include:
  - _pages
  - _includes
  - _img
